import { User, Client, Project, Task, Activity, DashboardStats, TaskStatusCount } from './types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'john@example.com',
    full_name: 'John Smith',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    is_active: true,
  },
  {
    id: '2',
    email: 'sarah@example.com',
    full_name: 'Sarah Johnson',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    is_active: true,
  },
  {
    id: '3',
    email: 'mike@example.com',
    full_name: 'Mike Wilson',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    is_active: true,
  },
  {
    id: '4',
    email: 'emma@example.com',
    full_name: 'Emma Davis',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    is_active: true,
  },
];

// Mock Clients
export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Acme Corporation',
    contact_person: 'Robert Brown',
    email: 'robert@acme.com',
    phone: '555-0101',
    company_name: 'Acme Corp',
  },
  {
    id: '2',
    name: 'TechStart Inc',
    contact_person: 'Lisa Anderson',
    email: 'lisa@techstart.com',
    phone: '555-0102',
    company_name: 'TechStart',
  },
  {
    id: '3',
    name: 'Global Solutions',
    contact_person: 'David Lee',
    email: 'david@globalsolutions.com',
    phone: '555-0103',
    company_name: 'Global Solutions Ltd',
  },
];

// Mock Projects
export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Q1 Marketing Campaign',
    client: mockClients[0],
    status: 'active',
    sales_person: mockUsers[0],
    ae: mockUsers[1],
    start_date: '2025-01-01',
    end_date: '2025-03-31',
    confirmed_at: '2024-12-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Website Redesign',
    client: mockClients[1],
    status: 'active',
    sales_person: mockUsers[2],
    ae: mockUsers[3],
    start_date: '2025-02-01',
    end_date: '2025-04-30',
    confirmed_at: '2025-01-20T14:30:00Z',
  },
  {
    id: '3',
    name: 'Social Media Package',
    client: mockClients[2],
    status: 'on_hold',
    sales_person: mockUsers[0],
    start_date: '2025-03-01',
  },
];

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: '1',
    project: mockProjects[0],
    title: 'Create landing page design',
    description: 'Design mockups for the new landing page with mobile responsive layout',
    type: 'graphic',
    status: 'in_progress',
    priority: 'high',
    assignee: mockUsers[1],
    reviewer: mockUsers[0],
    due_date: '2025-02-15',
    created_by: mockUsers[0],
    created_at: '2025-01-10T09:00:00Z',
    updated_at: '2025-01-25T14:30:00Z',
  },
  {
    id: '2',
    project: mockProjects[0],
    title: 'Write blog post about product features',
    description: '1500 words article highlighting new features',
    type: 'content',
    status: 'waiting_review',
    priority: 'normal',
    assignee: mockUsers[2],
    reviewer: mockUsers[1],
    due_date: '2025-02-10',
    created_by: mockUsers[0],
    created_at: '2025-01-12T10:00:00Z',
    updated_at: '2025-01-24T16:00:00Z',
  },
  {
    id: '3',
    project: mockProjects[1],
    title: 'Review homepage wireframes',
    type: 'review',
    status: 'sent_client',
    priority: 'urgent',
    assignee: mockUsers[3],
    due_date: '2025-02-05',
    created_by: mockUsers[2],
    created_at: '2025-01-15T11:00:00Z',
    updated_at: '2025-01-23T09:00:00Z',
  },
  {
    id: '4',
    project: mockProjects[0],
    title: 'Schedule Instagram posts for February',
    type: 'posting',
    status: 'backlog',
    priority: 'low',
    assignee: mockUsers[0],
    due_date: '2025-02-28',
    created_by: mockUsers[0],
    created_at: '2025-01-20T13:00:00Z',
    updated_at: '2025-01-20T13:00:00Z',
  },
  {
    id: '5',
    project: mockProjects[1],
    title: 'Design new logo variations',
    description: 'Create 3 logo variations with different color schemes',
    type: 'graphic',
    status: 'approved',
    priority: 'high',
    assignee: mockUsers[1],
    reviewer: mockUsers[2],
    due_date: '2025-01-30',
    created_by: mockUsers[2],
    created_at: '2025-01-08T08:00:00Z',
    updated_at: '2025-01-22T17:00:00Z',
  },
  {
    id: '6',
    project: mockProjects[0],
    title: 'Prepare monthly analytics report',
    type: 'other',
    status: 'feedback',
    priority: 'normal',
    assignee: mockUsers[3],
    reviewer: mockUsers[0],
    due_date: '2025-02-01',
    created_by: mockUsers[0],
    created_at: '2025-01-18T10:00:00Z',
    updated_at: '2025-01-24T12:00:00Z',
  },
  {
    id: '7',
    project: mockProjects[1],
    title: 'Update website content',
    description: 'Update About Us and Services pages with new copy',
    type: 'content',
    status: 'done',
    priority: 'normal',
    assignee: mockUsers[2],
    due_date: '2025-01-20',
    completed_at: '2025-01-19T15:00:00Z',
    created_by: mockUsers[2],
    created_at: '2025-01-05T09:00:00Z',
    updated_at: '2025-01-19T15:00:00Z',
  },
  {
    id: '8',
    project: mockProjects[0],
    title: 'Create email newsletter template',
    type: 'graphic',
    status: 'in_progress',
    priority: 'normal',
    assignee: mockUsers[1],
    due_date: '2025-02-12',
    created_by: mockUsers[0],
    created_at: '2025-01-22T11:00:00Z',
    updated_at: '2025-01-25T10:00:00Z',
  },
];

// Mock Activities
export const mockActivities: Activity[] = [
  {
    id: '1',
    entity_type: 'task',
    entity_id: '2',
    action: 'status_change',
    description: 'moved task to Waiting Review',
    created_by: mockUsers[2],
    created_at: '2025-01-24T16:00:00Z',
  },
  {
    id: '2',
    entity_type: 'task',
    entity_id: '1',
    action: 'comment',
    description: 'added a comment on "Create landing page design"',
    created_by: mockUsers[0],
    created_at: '2025-01-25T14:30:00Z',
  },
  {
    id: '3',
    entity_type: 'task',
    entity_id: '8',
    action: 'created',
    description: 'created new task "Create email newsletter template"',
    created_by: mockUsers[0],
    created_at: '2025-01-22T11:00:00Z',
  },
  {
    id: '4',
    entity_type: 'task',
    entity_id: '3',
    action: 'status_change',
    description: 'sent task to client for review',
    created_by: mockUsers[3],
    created_at: '2025-01-23T09:00:00Z',
  },
  {
    id: '5',
    entity_type: 'task',
    entity_id: '5',
    action: 'status_change',
    description: 'approved task "Design new logo variations"',
    created_by: mockUsers[2],
    created_at: '2025-01-22T17:00:00Z',
  },
  {
    id: '6',
    entity_type: 'project',
    entity_id: '2',
    action: 'created',
    description: 'created new project "Website Redesign"',
    created_by: mockUsers[2],
    created_at: '2025-01-20T14:30:00Z',
  },
  {
    id: '7',
    entity_type: 'task',
    entity_id: '7',
    action: 'completed',
    description: 'completed task "Update website content"',
    created_by: mockUsers[2],
    created_at: '2025-01-19T15:00:00Z',
  },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  total_tasks: mockTasks.length,
  active_projects: mockProjects.filter(p => p.status === 'active').length,
  completion_rate: Math.round((mockTasks.filter(t => t.status === 'done').length / mockTasks.length) * 100),
  overdue_tasks: mockTasks.filter(t => t.due_date && new Date(t.due_date) < new Date() && t.status !== 'done').length,
};

// Mock Task Status Counts
export const mockTaskStatusCounts: TaskStatusCount[] = [
  { status: 'backlog', count: mockTasks.filter(t => t.status === 'backlog').length },
  { status: 'in_progress', count: mockTasks.filter(t => t.status === 'in_progress').length },
  { status: 'waiting_review', count: mockTasks.filter(t => t.status === 'waiting_review').length },
  { status: 'sent_client', count: mockTasks.filter(t => t.status === 'sent_client').length },
  { status: 'feedback', count: mockTasks.filter(t => t.status === 'feedback').length },
  { status: 'approved', count: mockTasks.filter(t => t.status === 'approved').length },
  { status: 'done', count: mockTasks.filter(t => t.status === 'done').length },
];
